### ISSUE TITLE
Lumen v8

### ISSUE THREAD

**Issue by do6po** [eplightning/roadrunner-lumen#3]
Hi man. Add to support lumen with version 8 please.

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!

**Comment by eplightning** [comment]
I modified dependencies to allow use of Lumen 8 but since I have dropped RoadRunner from all my projects I don't have a quick way of testing it.
